import json
import os
import unittest
from datetime import datetime, timezone
from typing import Optional

from app.agents import (
    Critique,
    DestinationResearchAgent,
    ItineraryCriticAgent,
    TripCoordinatorAgent,
)
from app.planner import create_trip_plan
from app.runs import TripPlanRunStore
from app.schemas import (
    DestinationResearch,
    MemoryNote,
    TripDay,
    TripOption,
    TripPlanRequest,
    TripPlanResponse,
)
from app.tools import (
    DestinationResearchQuery,
    FareOption,
    FlightSearchQuery,
    ItineraryPlanningInput,
    ItineraryRevisionInput,
    OpenAIDestinationResearcher,
    OpenAIItineraryPlanner,
    OpenAIItineraryReviser,
    OpenAIPlannerConfig,
    TravelPlanningToolRouter,
    model_backed_destination_researcher,
    model_backed_itinerary_planner,
    rule_based_itinerary_reviser,
)


class TripPlannerTests(unittest.TestCase):
    def setUp(self) -> None:
        self.openai_api_key = os.environ.pop("OPENAI_API_KEY", None)

    def tearDown(self) -> None:
        if self.openai_api_key is not None:
            os.environ["OPENAI_API_KEY"] = self.openai_api_key

    def test_create_trip_plan_returns_contract_shape(self) -> None:
        request = make_request()

        response = create_trip_plan(request)

        self.assertEqual(len(response.trips), 3)
        self.assertEqual(response.trips[0].route, "New York -> Lisbon")
        self.assertEqual(response.trips[0].days[0].label, "D1")
        self.assertIsNotNone(response.memory)
        self.assertEqual(response.memory[-1].title, "Last best option")

    def test_create_trip_plan_routes_provider_functions(self) -> None:
        calls: list[str] = []
        saved_memory = [MemoryNote(title="Preference", detail="Likes culture walks.")]
        request = make_request(rememberPreferences=False, memory=saved_memory)

        def destination_researcher(query: DestinationResearchQuery) -> DestinationResearch:
            calls.append("research")
            self.assertEqual(query.destination, "Lisbon")
            self.assertEqual(query.mood, "Culture")
            self.assertEqual(query.memory, saved_memory)

            return make_destination_research()

        def flight_provider(query: FlightSearchQuery) -> list[FareOption]:
            calls.append("flight")
            self.assertEqual(query.origin, "New York")
            self.assertEqual(query.destination, "Lisbon")
            self.assertEqual(query.budget, 1400)

            return [
                FareOption(
                    name="Provider Fare",
                    fare=510,
                    score=97,
                    meta="provider fare",
                )
            ]

        def itinerary_planner(planning_input: ItineraryPlanningInput) -> list[TripOption]:
            calls.append("itinerary")
            self.assertEqual(planning_input.constraints, "Window seat, no red-eye flights.")
            self.assertEqual(planning_input.memory, saved_memory)
            self.assertEqual(planning_input.fares[0].name, "Provider Fare")
            self.assertEqual(
                planning_input.destination_research,
                make_destination_research(),
            )

            return [
                TripOption(
                    name="Provider Plan",
                    route="New York -> Lisbon",
                    fare=planning_input.fares[0].fare,
                    score=planning_input.fares[0].score,
                    meta="model planned",
                    days=[
                        TripDay(
                            label="D1",
                            title="Provider day",
                            detail="Generated by the injected planner.",
                        )
                    ],
                )
            ]

        tools = TravelPlanningToolRouter(
            flight_provider=flight_provider,
            itinerary_planner=itinerary_planner,
            destination_researcher=destination_researcher,
        )

        response = create_trip_plan(request, tools=tools)

        self.assertEqual(calls, ["research", "flight", "itinerary"])
        self.assertEqual(response.trips[0].name, "Provider Plan")
        self.assertEqual(response.memory, saved_memory)

    def test_destination_research_agent_routes_research_tool(self) -> None:
        calls: list[str] = []

        def destination_researcher(query: DestinationResearchQuery) -> DestinationResearch:
            calls.append(query.destination)
            return make_destination_research()

        tools = TravelPlanningToolRouter(
            flight_provider=lambda query: [],
            itinerary_planner=lambda planning_input: [],
            destination_researcher=destination_researcher,
        )
        agent = DestinationResearchAgent(tools)

        research = agent.run(make_request())

        self.assertEqual(calls, ["Lisbon"])
        self.assertEqual(research.summary, "Lisbon culture research.")

    def test_coordinator_revises_rejected_trip_once(self) -> None:
        request = make_request()
        tools = TravelPlanningToolRouter(
            flight_provider=lambda query: [
                FareOption(
                    name="Over Budget",
                    fare=1500,
                    score=93,
                    meta="test fare",
                )
            ],
            itinerary_planner=lambda planning_input: [
                TripOption(
                    name="Over Budget",
                    route="New York -> Lisbon",
                    fare=1500,
                    score=93,
                    meta="test fare",
                    days=[
                        TripDay(
                            label="D1",
                            title="Packed day",
                            detail="Museum, market, tram, castle, dinner.",
                        )
                    ],
                )
            ],
        )
        coordinator = TripCoordinatorAgent(
            tools=tools,
            critic_agent=RejectingCriticAgent(),
        )

        response = coordinator.run(request)

        self.assertEqual(len(response.trips), 1)
        self.assertIn("critic-reviewed", response.trips[0].meta)
        self.assertIn("revision-needs-review", response.trips[0].meta)
        self.assertNotIn("Critic revision", response.trips[0].days[-1].detail)
        self.assertIn("Prioritize free sights", response.trips[0].days[-1].detail)

    def test_coordinator_emits_agent_progress_events(self) -> None:
        events: list[tuple[str, str, str]] = []
        request = make_request()
        tools = TravelPlanningToolRouter(
            flight_provider=lambda query: [
                FareOption(
                    name="Provider Fare",
                    fare=510,
                    score=97,
                    meta="provider fare",
                )
            ],
            itinerary_planner=lambda planning_input: [
                TripOption(
                    name="Provider Plan",
                    route="New York -> Lisbon",
                    fare=planning_input.fares[0].fare,
                    score=planning_input.fares[0].score,
                    meta="model planned",
                    days=[
                        TripDay(
                            label="D1",
                            title="Provider day",
                            detail="Generated by the injected planner.",
                        )
                    ],
                )
            ],
            destination_researcher=lambda query: make_destination_research(),
        )
        coordinator = TripCoordinatorAgent(
            tools=tools,
            progress=lambda step, status, title, detail: events.append((step, status, title)),
        )

        response = coordinator.run(request)

        self.assertEqual(len(response.trips), 1)
        self.assertEqual(
            events,
            [
                ("research", "active", "Research destination"),
                ("research", "done", "Research destination"),
                ("flights", "active", "Search flights"),
                ("flights", "done", "Search flights"),
                ("itinerary", "active", "Build itinerary"),
                ("itinerary", "done", "Build itinerary"),
                ("critic", "active", "Critic review"),
                ("critic", "done", "Critic review"),
                ("revision", "done", "Revise if needed"),
                ("memory", "active", "Finalize memory"),
                ("memory", "done", "Finalize memory"),
            ],
        )

    def test_run_store_tracks_events_and_result(self) -> None:
        store = TripPlanRunStore()
        created = store.create()
        result = TripPlanResponse(trips=[], memory=[])

        store.emit(
            run_id=created.runId,
            step="research",
            status="active",
            title="Research destination",
        )
        store.emit(
            run_id=created.runId,
            step="research",
            status="done",
            title="Research destination",
        )
        store.complete(created.runId, result)

        snapshot = store.snapshot(created.runId)

        self.assertIsNotNone(snapshot)
        assert snapshot is not None
        self.assertEqual(snapshot.status, "completed")
        self.assertEqual(snapshot.result, result)
        self.assertEqual([event.status for event in snapshot.events], ["active", "done"])

    def test_rule_based_revision_rewrites_overpacked_day(self) -> None:
        request = make_request()
        trip = TripOption(
            name="Packed Plan",
            route="New York -> Lisbon",
            fare=620,
            score=93,
            meta="test fare",
            days=[
                TripDay(
                    label="D1",
                    title="Too much",
                    detail="Museum, market, tram, castle, dinner.",
                )
            ],
        )

        revised_trip = rule_based_itinerary_reviser(
            ItineraryRevisionInput(
                request=request,
                original_trip=trip,
                critic_score=76,
                issues=["D1 may be too packed for a mobile travel plan."],
                recommendations=["Add a protected break or reduce the number of activities."],
            )
        )

        self.assertEqual(revised_trip.name, trip.name)
        self.assertEqual(revised_trip.fare, trip.fare)
        self.assertIn("critic-reviewed", revised_trip.meta)
        self.assertEqual(
            revised_trip.days[0].detail,
            "Museum, market, then a protected break before dinner. "
            "Constraints honored: Window seat, no red-eye flights.",
        )

    def test_model_backed_planner_falls_back_without_api_key(self) -> None:
        planning_input = make_planning_input()

        trips = model_backed_itinerary_planner(planning_input)

        self.assertEqual(len(trips), 1)
        self.assertEqual(trips[0].name, "Provider Fare")
        self.assertEqual(trips[0].route, "New York -> Lisbon")

    def test_model_backed_researcher_falls_back_without_api_key(self) -> None:
        research = model_backed_destination_researcher(make_destination_research_query())

        self.assertEqual(research.destination, "Lisbon")
        self.assertIn("Lisbon", research.summary)
        self.assertEqual(len(research.highlights), 3)

    def test_openai_planner_request_body_uses_structured_outputs(self) -> None:
        planner = OpenAIItineraryPlanner(OpenAIPlannerConfig(api_key="test-key"))

        body = planner.request_body(make_planning_input())
        prompt_payload = json_from_body(body)

        self.assertEqual(body["model"], "gpt-5.5")
        self.assertEqual(body["reasoning"]["effort"], "low")
        self.assertFalse(body["store"])
        self.assertEqual(body["text"]["format"]["type"], "json_schema")
        self.assertEqual(body["text"]["format"]["name"], "travel_itinerary_options")
        self.assertTrue(body["text"]["format"]["strict"])
        self.assertEqual(prompt_payload["destinationResearch"]["destination"], "Lisbon")

    def test_openai_destination_research_request_body_uses_structured_outputs(self) -> None:
        researcher = OpenAIDestinationResearcher(OpenAIPlannerConfig(api_key="test-key"))

        body = researcher.request_body(make_destination_research_query())
        prompt_payload = json_from_body(body)

        self.assertEqual(body["model"], "gpt-5.5")
        self.assertEqual(body["reasoning"]["effort"], "low")
        self.assertFalse(body["store"])
        self.assertEqual(body["text"]["format"]["type"], "json_schema")
        self.assertEqual(body["text"]["format"]["name"], "destination_research")
        self.assertTrue(body["text"]["format"]["strict"])
        self.assertEqual(prompt_payload["trip"]["destination"], "Lisbon")
        self.assertIn("Prefer experience types", prompt_payload["successCriteria"][1])

    def test_openai_revision_request_body_uses_critique_context(self) -> None:
        reviser = OpenAIItineraryReviser(OpenAIPlannerConfig(api_key="test-key"))

        body = reviser.request_body(
            ItineraryRevisionInput(
                request=make_request(),
                original_trip=TripOption(
                    name="Packed Plan",
                    route="New York -> Lisbon",
                    fare=620,
                    score=93,
                    meta="test fare",
                    days=[
                        TripDay(
                            label="D1",
                            title="Too much",
                            detail="Museum, market, tram, castle, dinner.",
                        )
                    ],
                ),
                critic_score=76,
                issues=["D1 may be too packed for a mobile travel plan."],
                recommendations=["Add a protected break or reduce the number of activities."],
                destination_research=make_destination_research(),
            )
        )
        prompt_payload = json_from_body(body)

        self.assertEqual(body["text"]["format"]["name"], "travel_itinerary_revision")
        self.assertTrue(body["text"]["format"]["strict"])
        self.assertEqual(prompt_payload["originalTrip"]["name"], "Packed Plan")
        self.assertEqual(prompt_payload["critique"]["score"], 76)
        self.assertEqual(prompt_payload["destinationResearch"]["summary"], "Lisbon culture research.")
        self.assertIn("Return exactly one revised option", prompt_payload["successCriteria"][0])


class RejectingCriticAgent(ItineraryCriticAgent):
    def run(
        self,
        request: TripPlanRequest,
        trip: TripOption,
    ) -> Critique:
        return Critique(
            approved=False,
            score=72,
            issues=["Trip is over budget."],
            recommendations=["Add a budget-safe revision note."],
        )


def make_request(
    rememberPreferences: bool = True,
    memory: Optional[list[MemoryNote]] = None,
) -> TripPlanRequest:
    return TripPlanRequest(
        origin="New York",
        destination="Lisbon",
        departDate=datetime(2026, 7, 11, 9, tzinfo=timezone.utc),
        returnDate=datetime(2026, 7, 16, 9, tzinfo=timezone.utc),
        budget=1400,
        constraints="Window seat, no red-eye flights.",
        rememberPreferences=rememberPreferences,
        mood="Culture",
        memory=memory or [],
    )


def make_planning_input() -> ItineraryPlanningInput:
    request = make_request(memory=[MemoryNote(title="Preference", detail="Likes culture walks.")])

    return ItineraryPlanningInput(
        origin=request.origin,
        destination=request.destination,
        depart_date=request.departDate,
        return_date=request.returnDate,
        budget=request.budget,
        duration=5,
        mood=request.mood,
        constraints=request.constraints,
        memory=request.memory,
        fares=[
            FareOption(
                name="Provider Fare",
                fare=510,
                score=97,
                meta="provider fare",
            )
        ],
        destination_research=make_destination_research(),
    )


def make_destination_research() -> DestinationResearch:
    return DestinationResearch(
        destination="Lisbon",
        summary="Lisbon culture research.",
        highlights=[
            "Tile museum",
            "Old town walk",
            "Riverfront concert",
        ],
        cautions=[
            "Avoid stacking too many cross-town activities into one day.",
        ],
        local_tips=[
            "Hold one open block for local recommendations.",
        ],
    )


def make_destination_research_query() -> DestinationResearchQuery:
    request = make_request(memory=[MemoryNote(title="Preference", detail="Likes culture walks.")])

    return DestinationResearchQuery(
        origin=request.origin,
        destination=request.destination,
        depart_date=request.departDate,
        return_date=request.returnDate,
        budget=request.budget,
        mood=request.mood,
        constraints=request.constraints,
        memory=request.memory,
    )


def json_from_body(body: dict) -> dict:
    return json.loads(body["input"][1]["content"])


if __name__ == "__main__":
    unittest.main()
