from datetime import datetime, timezone
from typing import Optional
import unittest

from app.planner import create_trip_plan
from app.schemas import MemoryNote, TripDay, TripOption, TripPlanRequest
from app.tools import (
    FareOption,
    FlightSearchQuery,
    ItineraryPlanningInput,
    TravelPlanningToolRouter,
)


class TripPlannerTests(unittest.TestCase):
    def test_create_trip_plan_returns_contract_shape(self) -> None:
        request = make_request()

        response = create_trip_plan(request)

        self.assertEqual(len(response.trips), 3)
        self.assertEqual(response.trips[0].route, "New York -> Lisbon")
        self.assertEqual(response.trips[0].days[0].label, "D1")
        self.assertIsNotNone(response.memory)
        self.assertEqual(response.memory[-1].title, "Last best option")

    def test_create_trip_plan_routes_provider_functions(self) -> None:
        calls: list[str] = []
        saved_memory = [MemoryNote(title="Preference", detail="Likes culture walks.")]
        request = make_request(rememberPreferences=False, memory=saved_memory)

        def flight_provider(query: FlightSearchQuery) -> list[FareOption]:
            calls.append("flight")
            self.assertEqual(query.origin, "New York")
            self.assertEqual(query.destination, "Lisbon")
            self.assertEqual(query.budget, 1400)

            return [
                FareOption(
                    name="Provider Fare",
                    fare=510,
                    score=97,
                    meta="provider fare",
                )
            ]

        def itinerary_planner(planning_input: ItineraryPlanningInput) -> list[TripOption]:
            calls.append("itinerary")
            self.assertEqual(planning_input.constraints, "Window seat, no red-eye flights.")
            self.assertEqual(planning_input.memory, saved_memory)
            self.assertEqual(planning_input.fares[0].name, "Provider Fare")

            return [
                TripOption(
                    name="Provider Plan",
                    route="New York -> Lisbon",
                    fare=planning_input.fares[0].fare,
                    score=planning_input.fares[0].score,
                    meta="model planned",
                    days=[
                        TripDay(
                            label="D1",
                            title="Provider day",
                            detail="Generated by the injected planner.",
                        )
                    ],
                )
            ]

        tools = TravelPlanningToolRouter(
            flight_provider=flight_provider,
            itinerary_planner=itinerary_planner,
        )

        response = create_trip_plan(request, tools=tools)

        self.assertEqual(calls, ["flight", "itinerary"])
        self.assertEqual(response.trips[0].name, "Provider Plan")
        self.assertEqual(response.memory, saved_memory)


def make_request(
    rememberPreferences: bool = True,
    memory: Optional[list[MemoryNote]] = None,
) -> TripPlanRequest:
    return TripPlanRequest(
        origin="New York",
        destination="Lisbon",
        departDate=datetime(2026, 7, 11, 9, tzinfo=timezone.utc),
        returnDate=datetime(2026, 7, 16, 9, tzinfo=timezone.utc),
        budget=1400,
        constraints="Window seat, no red-eye flights.",
        rememberPreferences=rememberPreferences,
        mood="Culture",
        memory=memory or [],
    )


if __name__ == "__main__":
    unittest.main()
